version: "3.8"

services:
  postgre:
    image: postgres:12.17
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: Pg123
      POSTGRES_USER: kubenews
      POSTGRES_DB: kubenews
    volumes:
      - postgre_docker_vol:/var/lib/postgresql/data
    networks:
      - kube_news_net

  kube_news:
    image: kubedevio/kube-news:v1
    ports:
      - 8080:8080
    networks:
      - kube_news_net
    environment:
      DB_PASSWORD: Pg123
      DB_USERNAME: kubenews
      DB_DATABASE: kubenews
      DB_HOST: postgre
    depends_on:
      - postgre

volumes:
  postgre_docker_vol:
    name: my_ext_postgre_vol
    external: true

networks:
  kube_news_net:
    name: knew_net
    external: true
    driver: bridge
